package com.franchiseworld.jalad.model;

import java.time.LocalDate;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Data
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long orderId;
    private Long shippingId;           //make it as autogenerated
    private LocalDate orderDate;      
    private String createdBy;        //name of placer
    private String pickupAddress;
    private String deliveryAddress;
    private Status status;           


}
